### PR TITLE
returns memcached_up = 0 when fail to parse a stats values.

### LINKED ISSUE #38: Don't use NaNs as error values
NaNs should only be used in cases where they make mathematical sense. If there's an error you should generally fail the scrape or set up to 0.

See https://stackoverflow.com/questions/53430836/prometheus-sum-one-nan-value-result-into-nan-how-to-avoid-it/

### PR DESCRIPTION
**Pull request by f110**
fix #38

If there's an error when parse a stats value, returns `memcached_up = 0`.
because other metrics which succeeded in parsing value are useful. 

If the LRU crawler does not run, ignoring some keys of related to it.

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -675,6 +765,15 @@ func sum(stats map[string]string, keys ...string) (float64, error) {
 	return s, nil
 }
 
+func hasError(errors ...error) error {
```
Comment (grobie) [inline main.go]: This method would be more accurately named `firstError`. `hasError` indicates it would return a boolean.

File: main.go [hunk 2]
```diff
@@ -551,115 +579,177 @@ func (e *Exporter) Collect(ch chan<- prometheus.Metric) {
...
-		return 1
+		return 1, nil
 	case "no":
-		return 0
+		return 0, nil
 	default:
-		log.Errorf("Failed parse %s %q", key, stats[key])
-		return math.NaN()
+		log.Errorf("Failed parse %s %q", key, value)
+		return math.NaN(), errors.New("failed parse a bool value")
```
Comment (grobie) [inline main.go]: It'd be more idiomatic to return 0 for the float64, as that's the default value, instead of returning NaN.

File: main.go [hunk 3]
```diff
@@ -551,115 +579,177 @@ func (e *Exporter) Collect(ch chan<- prometheus.Metric) {
...
+	return nil
 }
 
-func parse(stats map[string]string, key string) float64 {
-	v, err := strconv.ParseFloat(stats[key], 64)
+func parse(stats map[string]string, key string) (float64, error) {
+	value, ok := stats[key]
+	if !ok {
+		log.Errorf("Key not found: %s", key)
+		return math.NaN(), errors.New("key not found")
```
Comment (grobie) [inline main.go]: New metrics added to the exporter might not be available in older memcached versions, so returning a hard error will break the exporter for such users. IIRC the touch command was only added later to memcached for example, so not being able to lookup the metric will cause an error. In order to keep the exporter compatible with older versions, we'd need to handle such errors more gracefully.

Comment (f110) [reply main.go]: I agree.

So an error occur when failed parse a value only.

Comment (f110) [reply main.go]: And I had try to support other daemon which implement memcached protocol (e,g, InnoDB memcached plugin).
But it's impossible. because memcached client library does not support it.

**Comment by f110** [comment]
Thank you for your review.

I fixed a compatible and some problems.
Could you please review again?

**Comment by f110** [comment]
@grobie ping

**Comment by f110** [comment]
@grobie Is there anything else to need for merging?

File: main.go [hunk 4]
```diff
@@ -532,149 +550,235 @@ func (e *Exporter) Collect(ch chan<- prometheus.Metric) {
...
+	ch <- prometheus.MustNewConstMetric(desc, valueType, v, labelValues...)
+	return nil
 }
 
-func parse(stats map[string]string, key string) float64 {
-	v, err := strconv.ParseFloat(stats[key], 64)
+func parse(stats map[string]string, key string) (float64, error) {
+	value, ok := stats[key]
+	if !ok {
+		log.Errorf("Key not found: %s", key)
```
Comment (grobie) [inline main.go]: I don't think we should log unavailable keys as errors, as this will be very noisy for older memcached versions. I believe only issues which should not occur for any supported memcached version should be logged as errors, like connection errors or failures to parse a returned value.

I suggest to use the debug level to log unavilable keys.

**Comment by f110** [comment]
@grobie Thank you for review!

You are right!
This log is very noisy for older memcached. for example memcached 1.4.17 doesn't have the stats which relevant to `lru_crawler` ( `lru_crawler_starts`, `crawler_items_checked` etc...)

And, There is already to output very noisy log by the previous my PR (#49). So i decided to fix that problem too on this PR.

**Comment by grobie** [comment]
Thanks a lot for your contribution @f110. I squashed your commits together for readability and will release a new version shortly.

**Comment by f110** [comment]
Thank you for the merge.
And I appreciate your patience for my English.

**Comment by grobie** [comment]
Version v0.6.0 has been published https://groups.google.com/forum/#!topic/prometheus-announce/INfriYx3o1g

Thanks again @f110 and don't worry at all, your comments were easy to read and understand.
